### ISSUE TITLE
[Feature-Request] Add the possibility to use it without bearer token

### ISSUE THREAD

**Issue by VfBfoerst** [ParisNeo/ollama_proxy_server#1]
Hi :)  
Just found your project and it seems to be exactly the project I was looking for. Cool!  
It would be nice if there was an option to opt out the authorization feature (or is it already there?), as many ollama projects, e.g. the [ollama-webui](https://github.com/ollama-webui/ollama-webui), don't support the bearer Token yet. So opting out would be really nice to use your project with ollama-projects that don't support it yet.  
  
Thank you! :)

**Comment by ParisNeo** [comment]
Done,

Just run the script with --deactivate_security or -d.

**Comment by ParisNeo** [comment]
You are welcome
