### ISSUE TITLE
Unexpected non-whitespace character after JSON at position 214

### ISSUE THREAD

**Issue by overflowrepo** [ParisNeo/ollama_proxy_server#11]
So close to having this working.

Proxy and ollama are on different machines, I have gone though a number of issues, for instance it seems to want a real host rather than just an IP address.

But down now down to this error, I am using Chaxbox on a third machine, for the connection. It connects to  LLM studio fine.

Unexpected non-whitespace character after JSON at position 214

Thanks

**Comment by ParisNeo** [comment]
it wants a full path, you can have http://ip_address:port_number.
in which json file do you get this error?

**Comment by overflowrepo** [comment]
This was an error with that particular client, so on the client side, thanks. Working well.

I do have another question about running the docker image.
You say "docker run -d --name ollama-proxy-server -p 8080:8080 ollama_proxy_server:latest"
This starts the image running for me, but I no longer connect to it like this. Are there other commands I must include? As it connects fine with this python3 ollama_proxy_server/main.py --config [configuration file path] --users_list [users list file path] --port [port number to access the proxy], but not this:  docker run -d --name ollama-proxy-server -p 8080:8080 ollama_proxy_server:latest

Sorry, as you can tell I am a bit of a newb with docker etc.
