### ISSUE TITLE
case-sensitive http headers

### ISSUE THREAD

**Issue by theoden8** [ParisNeo/ollama_proxy_server#12]
It seems that the header keys are camelcase, while according to https://www.rfc-editor.org/rfc/rfc7230 header fields are case-insensitive. This leads to 403.

Example:

https://github.com/ParisNeo/ollama_proxy_server/blob/main/ollama_proxy_server/main.py#L101
https://github.com/ParisNeo/ollama_proxy_server/blob/main/ollama_proxy_server/main.py#L123

Related: https://github.com/Mobile-Artificial-Intelligence/maid/issues/530#issuecomment-2106339582

**Comment by theoden8** [comment]
The issue was bearer token, apologies.

**Comment by ParisNeo** [comment]
No problem
